In [9]:
import tensorflow as tf

# --------------- 1. 关闭 Eager，只用 Graph ---------------
tf.compat.v1.disable_eager_execution()          # 如果你是 TF 2.x，可选；TF 1.x 可忽略

# --------------- 2. 构图 ---------------
x = tf.constant([[-1.0, 0.0],
                 [150.0,   10.0],
                 [  5.0,  100.0]])

buckets = tf.raw_ops.Bucketize(input=x,
                               boundaries=[0.0, 10.0, 100.0])   # Tensor[int32]

# (可选) one-hot 离散化
one_hot = tf.one_hot(buckets, depth=4)          # 因为 3 个边界 ⇒ 4 个桶

# --------------- 3. 运行 Session ---------------
with tf.compat.v1.Session() as sess:
    buckets_val, one_hot_val = sess.run([buckets, one_hot])
    print("bucket ids:\n", buckets_val)
    print("one-hot:\n", one_hot_val)


bucket ids:
 [[0 1]
 [3 2]
 [1 3]]
one-hot:
 [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]]]


In [ ]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

matrix  = [10,11,12]        
row_idx = tf.constant([2, 0])          

rows = tf.gather(matrix, row_idx)          # shape [2,3]

with tf.compat.v1.Session() as sess:
    print(sess.run(rows))

[12 10]
Tensor("GatherV2_1:0", shape=(2,), dtype=int32)


In [1]:
import numpy as np

In [11]:
x = np.array([-1e6, -1e6, -1e6])

In [12]:
x

array([-1000000., -1000000., -1000000.])

In [16]:
np.exp(x)
np.sum(np.exp(x))

0.0

In [21]:
np.exp(x) / (np.sum(np.exp(x)) + 1e-9)

array([0., 0., 0.])

In [24]:
np.array(1) / np.array(0) 

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


inf

In [31]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()  # TF1.x 常见：用 session 跑

x = tf.constant([-1e9, -1e9, -1e6])

y = tf.nn.softmax(x)

z = tf.exp(x)

m = z / tf.reduce_sum(z)

with tf.compat.v1.Session() as sess:
    x, y, z, m = sess.run([x,y,z,m])
    print(x)
    print(y)
    print(z)
    print(m)   

[-1.e+09 -1.e+09 -1.e+06]
[0. 0. 1.]
[0. 0. 0.]
[nan nan nan]


In [19]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()  # TF1.x 常见：用 session 跑

x = tf.constant([[1, 2],[3, 4],[5, 6]])

y = x[:,None,:]

z = tf.broadcast_to(x[:, None, :], (3,2,2))
# y = tf.nn.softmax(x)

# z = tf.exp(x)

m = tf.reshape(tf.repeat(x, 2, axis=1), (3,2,2))

n = tf.reshape(tf.tile(x, (1,2)), (3,2,2))

with tf.compat.v1.Session() as sess:
    x, y, z, m, n= sess.run([x,y,z,m,n])
    print(x)
    print(y)
    print(z)
    print(m)
    print(n)

[[1 2]
 [3 4]
 [5 6]]
[[[1 2]]

 [[3 4]]

 [[5 6]]]
[[[1 2]
  [1 2]]

 [[3 4]
  [3 4]]

 [[5 6]
  [5 6]]]
[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]

 [[5 5]
  [6 6]]]
[[[1 2]
  [1 2]]

 [[3 4]
  [3 4]]

 [[5 6]
  [5 6]]]
